layouts:
  - layout: 
      path: layout
  - header: 
      path: header
  - nav_main: 
      path: nav_main
  - sidebar: 
      path: sidebar

pages:
  rf-labels:
    index-page: index.html
    layout: "chunk:1"

  index.html:
    path: index.html
    rf-labels:
      active_menu_item: "1" 

  chronicle.html: 
    path: chronicle.html
    rf-labels:
      active_menu_item: "2" 

  pond.html: 
    content: |
      <h1>Pond</h>
      <a href="http://groups.google.com/group/railfrog-dev">Pond</a>

    rf-labels:
      active_menu_item: "3" 
  test_dir01:
    rf-labels:
      test-dir01-label01: test-dir01-value01
      test-dir01-label02: test-dir01-value02
    test_dir02:
      rf-labels:
        test-dir02-label01: test-dir02-value01
        test-dir02-label02: test-dir02-value02
  test_dir03:
    rf-labels:
      test-dir03-label01: test-dir03-value01
      test-dir03-label02: test-dir03-value02
    test_dir04:
      rf-labels:
        test-dir04-label01: test-dir04-value01
        test-dir04-label02: test-dir04-value02
      test_file01.html:
        content: |
          <h1>Test</h1>
          <p>We love testing!</p>
        rf-labels:
          test-file01-label01: test-file01-value01
          test-file01-label01: test-file01-value01
          
      


